IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'POWERPLAY\IT-Dev-Devices')
CREATE LOGIN [POWERPLAY\IT-Dev-Devices] FROM WINDOWS
GO
CREATE USER [POWERPLAY\IT-Dev-Devices] FOR LOGIN [POWERPLAY\IT-Dev-Devices]
GO
